services:
  rabbitmq:
    container_name: rabbitmq-platform-rabbitmq
    image: rabbitmq:3.10.7-management
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASSWORD}
    networks:
      - platform
    ports:
      - "15672:15672"
      - "5672:5672"

networks:
  platform:
    driver: bridge